# Generated by Django 6.0.3 on 2026-04-04 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sizes',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('shirt', 'Shirt'), ('tshirt', 'Tshirt'), ('pant', 'Pant'), ('shoe', 'Shoe'), ('slipper', 'Slipper'), ('chain', 'Chain'), ('watch', 'Watch'), ('ring', 'Ring'), ('belt', 'Belt')], max_length=20),
        ),
    ]
